

server:
  port: 8081

spring:
  application:
    name: compute-service
  datasource:
    url: jdbc:mysql://localhost:3306/world?serverTimezone=UTC&useUnicode=true&charaterEncoding=utf-8&useSSL=false
    username: root
    password: 666666
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: native
  cloud:
    bus:
      trace:
        enabled: true
      enabled: true
    config:
      label: master
      profile: dev
      uri: http://localhost:8083/
management:
  endpoints:
    web:
      exposure:
        include: "*"


eureka:
  client:
    enabled: true
    service-url:
      #defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
      defaultZone: http://localhost:8761/eureka/

mybatis:
  mapper-locations: /mapper/**/**.xml
redis:
  # Redis数据库索引（默认为0）
  database: 0
  # Redis服务器地址
  host: 127.0.0.1
  # Redis服务器连接端口
  port: 6379
  # Redis服务器连接密码（默认为空）
  password:
  #jedis:
  lettuce:
    pool:
      #连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -2
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 300


feign:
  hystrix:
    enabled: true
